### PR TITLE
Cash register

### PR DESCRIPTION
**Pull request by Najeeba-Qarqin**
Cash Register App created in HTML, CSS and javaScript  cash register app that will return change to the customer based on the price of the item, the amount of cash provided by the customer, and the amount of cash in the cash drawer.

Annotation 2024-07-08 221151

### CODE REVIEW

**Comment by Najeeba-Qarqin** [comment]
Hi @Hasinarahman 
Place review my project.

**Comment by Hasinarahman** [comment]
Hello @Najeeba-Qarqin 
Excellent work
but your code is not pass in FreeCodeComp.

**Comment by Najeeba-Qarqin** [comment]
> Hello @Najeeba-Qarqin Excellent work but your code is not pass in FreeCodeComp.

**Comment by Najeeba-Qarqin** [comment]
Hi @Hasinarahman ok thank you for your feedback I'll implement your feedback .

**Comment by Najeeba-Qarqin** [comment]
Hi @Hasinarahman my codes passes the free code camp test now please review again. 
Thank you for your patience.

**Comment by Hasinarahman** [comment]
Hello @Najeeba-Qarqin 
now your project is apprived you can mention the mentor.

**Comment by Najeeba-Qarqin** [comment]
Hi @ahzamir 
Please review my project.

**Review by ahzamir — APPROVED** [review]
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
